DOCS_MD: list[str] = [
    "The deployment of smart grid tech optimizes wind and solar storage distribution.",
    "Renewable energy grids rely heavily on predictive machine learning algorithms.",
    "Battery backup power management cuts emissions in modernized electrical grids.",
    "Doctors are utilizing machine learning to predict patient heart disease risks.",
    "Advanced clinical diagnostics tools are transforming modern healthcare systems.",
    "Medical AI algorithms assist radiologists in finding early-stage lung tumors.",
    "Central banks are adjusting interest rates to combat rising global inflation.",
    "Stock market volatility increased following the federal reserve interest hike.",
    "Macroeconomic indicators suggest retail consumer spending is slowing down.",
]

DOCS_LG: list[str] = [
    # --- Cluster: Renewable Energy / Smart Grids (original + expanded) ---
    "The deployment of smart grid tech optimizes wind and solar storage distribution.",
    "Renewable energy grids rely heavily on predictive machine learning algorithms.",
    "Battery backup power management cuts emissions in modernized electrical grids.",
    "Smart grid infrastructure enables real-time load balancing across renewable sources.",
    "Wind farm operators use AI forecasting to predict turbine output and grid demand.",
    "Solar panel efficiency has improved dramatically with new photovoltaic materials.",
    "Energy storage solutions like lithium-ion batteries stabilize intermittent renewable supply.",
    "Microgrid systems allow remote communities to operate independently from main power lines.",
    "Hydropower plants complement solar and wind by providing consistent baseline energy.",
    "Grid operators deploy automated switching systems to prevent cascading power failures.",
    "Smart meters give consumers detailed insights into their hourly electricity consumption.",
    "Vehicle-to-grid technology lets electric cars feed power back during peak demand hours.",
    "Offshore wind farms harness stronger and more consistent ocean breezes than land turbines.",
    "Green hydrogen production uses excess renewable energy to create storable clean fuel.",
    "Thermal energy storage captures solar heat for electricity generation after sunset.",
    "Demand response programs incentivize factories to reduce power usage during grid strain.",
    "Transmission line monitoring drones detect faults before they cause widespread blackouts.",
    "Floating solar farms on reservoirs reduce water evaporation while generating clean power.",
    "Geothermal plants tap underground heat for reliable round-the-clock renewable electricity.",
    "Blockchain-based energy trading lets neighbors buy and sell excess rooftop solar power.",
    # --- Cluster: Healthcare / Medical AI (original + expanded) ---
    "Doctors are utilizing machine learning to predict patient heart disease risks.",
    "Advanced clinical diagnostics tools are transforming modern healthcare systems.",
    "Medical AI algorithms assist radiologists in finding early-stage lung tumors.",
    "Deep learning models analyze retinal scans to detect diabetic retinopathy early.",
    "Natural language processing extracts patient history from unstructured clinical notes.",
    "Wearable health monitors track vital signs and alert physicians to cardiac anomalies.",
    "AI-powered pathology tools identify cancerous cells in biopsy slides with high accuracy.",
    "Robotic surgery systems enhance precision in minimally invasive laparoscopic procedures.",
    "Drug discovery pipelines use molecular simulation to screen billions of compound candidates.",
    "Telemedicine platforms connect rural patients with specialists through video consultations.",
    "Electronic health records aggregate population data to identify emerging disease outbreaks.",
    "Chatbot triage systems help patients assess symptoms before visiting emergency rooms.",
    "Genomic sequencing combined with AI predicts individual responses to chemotherapy drugs.",
    "3D-printed prosthetics customized through computer vision offer affordable limb replacements.",
    "Predictive models forecast hospital admission rates during seasonal influenza peaks.",
    "Brain-computer interfaces restore communication for patients with severe motor disabilities.",
    "Automated insulin pumps adjust dosage in real-time using continuous glucose monitors.",
    "Radiomics extracts quantitative features from CT scans invisible to the human eye.",
    "Mental health apps use sentiment analysis to detect early signs of depressive episodes.",
    "Surgical planning software creates 3D organ models from MRI data for pre-operative practice.",
    # --- Cluster: Finance / Economics (original + expanded) ---
    "Central banks are adjusting interest rates to combat rising global inflation.",
    "Stock market volatility increased following the federal reserve interest hike.",
    "Macroeconomic indicators suggest retail consumer spending is slowing down.",
    "Cryptocurrency markets experienced sharp corrections after regulatory crackdown announcements.",
    "Bond yield curves inverted for the first time since the last major recession warning.",
    "Hedge funds deploy quantitative trading algorithms to exploit microsecond arbitrage windows.",
    "Mortgage applications dropped sharply as lending rates reached decade-high thresholds.",
    "Emerging market currencies weakened against the dollar amid tightening monetary policies.",
    "Consumer price index reports show persistent inflation in shelter and food categories.",
    "Venture capital funding for early-stage startups declined for three consecutive quarters.",
    "Credit default swap spreads widened on concerns over commercial real estate loan defaults.",
    "Central bank digital currencies promise faster settlement and programmable monetary policy.",
    "High-frequency trading firms account for over half of daily equity market volume.",
    "Sovereign wealth funds rebalance portfolios toward infrastructure and renewable energy assets.",
    "Inflation-linked bonds offer protection against purchasing power erosion for risk-averse investors.",
    "Algorithmic credit scoring uses alternative data to assess borrowers without traditional histories.",
    "Options market implied volatility spiked ahead of uncertain national election outcomes.",
    "Peer-to-peer lending platforms disintermediate banks by connecting borrowers with retail investors.",
    "Dark pool trading venues allow institutional investors to execute large blocks with minimal impact.",
    "Real-time payment systems reduce settlement times from days to seconds in modern economies.",
    # --- Outliers: deliberately dissimilar, each unique ---
    "The migration patterns of monarch butterflies span multiple generations across North America.",
    "Chefs recommend tempering dark chocolate slowly to achieve a glossy professional finish.",
    "Archaeologists unearthed a Viking burial ship containing well-preserved wooden carvings.",
    "Olympic marathon runners follow strict carbohydrate-loading regimens before race day.",
    "Urban beekeeping initiatives boost pollinator populations in densely populated city centers.",
    "Vinyl record sales surpassed CD revenue for the first time since the late 1980s.",
    "Amateur astronomers gathered to observe the rare transit of Venus across the solar disk.",
    "The acoustic properties of Stradivarius violins remain a subject of scientific investigation.",
    "Permaculture farming integrates fruit trees, livestock, and vegetable beds into closed-loop systems.",
    "Competitive memory athletes use the method of loci to recall thousands of random digits.",
]
